package com.architect.poc.transformers;

import com.architect.poc.pipelines.EnterpriseEvent;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.regex.Pattern;

public class PayloadTransformer implements Serializable {

    // Compile rapid text extraction patterns once to preserve task slot performance
    private static final Pattern SLACK_URL_CLEANER = Pattern.compile("<https?://[^>|]+\\|([^>]+)>|<(https?://[^>]+)>");
    private static final Pattern MARKDOWN_STRIPPER = Pattern.compile("[\\*\\_\\~\\`\\[\\]\\(\\)\\#\\+\\-\\=\\|\\{\\}]");

    public EnterpriseEvent transform(EnterpriseEvent input) {
        if (input == null || input.rawPayload == null) {
            return input;
        }

        switch (input.sourceSystem.toLowerCase()) {
            case "slack":
                return transformSlackPayload(input);
            case "salesforce":
                return transformSalesforceCDC(input);
            case "teams":
                return transformTeamsPayload(input);
            default:
                return sanitizeDefaultPayload(input);
        }
    }

    /**
     * Slack Transformation Matrix:
     * Compacts informal conversational data, extracts raw link targets, and flags mentions.
     */
    private EnterpriseEvent transformSlackPayload(EnterpriseEvent event) {
        String raw = event.rawPayload;

        // 1. Strip raw channel/user markdown tags to improve semantic vector density
        String cleanText = SLACK_URL_CLEANER.matcher(raw).replaceAll("$1$2");
        cleanText = MARKDOWN_STRIPPER.matcher(cleanText).replaceAll("");

        // 2. Set operational metrics
        event.rawPayload = cleanText.trim();
        event.metadataCategory = "collaboration-chat-msg";

        return event;
    }

    /**
     * Salesforce CDC Transformation Matrix:
     * Restructures multi-line database mutations and state deltas into clean, searchable syntax.
     */
    private EnterpriseEvent transformSalesforceCDC(EnterpriseEvent event) {
        String rawJson = event.rawPayload;

        // Enterprise Pattern: Instead of dropping flat JSON strings into the LLM context,
        // serialize database fields into a structured operational sentence string for high search precision.
        StringBuilder structuralBody = new StringBuilder();
        structuralBody.append("Salesforce Record Modification Verified. ");

        if (rawJson.contains("Opportunity")) {
            event.metadataCategory = "crm-sales-opportunity";
            structuralBody.append("Entity Type: Sales Opportunity. Details: ");
        } else if (rawJson.contains("Case")) {
            event.metadataCategory = "crm-customer-support-case";
            structuralBody.append("Entity Type: Escalated Support Case. Details: ");
        } else {
            event.metadataCategory = "crm-generic-datastore";
            structuralBody.append("Entity Type: Core Object Account Data. Details: ");
        }

        // Strip payload characters and structure remaining body block
        String fieldStripper = MARKDOWN_STRIPPER.matcher(rawJson).replaceAll(" ");
        structuralBody.append(fieldStripper.substring(0, Math.min(fieldStripper.length(), 500)));

        event.rawPayload = structuralBody.toString();
        return event;
    }

    /**
     * Microsoft Teams Transformation Matrix
     */
    private EnterpriseEvent transformTeamsPayload(EnterpriseEvent event) {
        // Strip nested HTML markup wrappers commonly generated by Teams message formats
        String htmlStripped = event.rawPayload.replaceAll("<[^>]*>", " ");

        event.rawPayload = htmlStripped.replaceAll("\\s+", " ").trim();
        event.metadataCategory = "collaboration-teams-msg";
        return event;
    }

    /**
     * Standard Safety Fallback Boundary Matrix
     */
    private EnterpriseEvent sanitizeDefaultPayload(EnterpriseEvent event) {
        event.rawPayload = event.rawPayload.strip();
        event.metadataCategory = "unclassified-enterprise-datum";
        return event;
    }
}